version: '3.8'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: onboarding_postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - onboarding_postgres_data:/var/lib/postgresql/data

volumes:
  onboarding_postgres_data: