services:
  postgres:
    image: postgres:15
    container_name: onboarding_postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - onboarding_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: onboarding_redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - onboarding_redis_data:/data

volumes:
  onboarding_postgres_data:
  onboarding_redis_data:
